# Generated by Django 5.2.6 on 2025-10-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JigsawExample",
            fields=[
                ("index", models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=30, verbose_name="name")),
                ("description", models.TextField(max_length=1000)),
            ],
            options={
                "db_table": "jigsaw_example",
            },
        ),
    ]
