# Generated by Django 5.2.6 on 2025-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JigsawExampleImage",
            fields=[
                ("index", models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ("url", models.URLField()),
                ("alt_text", models.CharField(max_length=140)),
            ],
            options={
                "db_table": "jigsaw_example_image",
            },
        ),
    ]
