# Generated by Django 5.2.6 on 2025-10-22 22:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_jigsawexampleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jigsawexample",
            name="index",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="jigsawexampleimage",
            name="index",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
