# Generated by Django 5.2.6 on 2025-10-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_alter_jigsawexample_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jigsawexample",
            name="images",
            field=models.ManyToManyField(to="models.jigsawexampleimage"),
        ),
    ]
